<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ChangesBuildHelper' => 'applications/changes/helper/ChangesBuildHelper.php',
    'ChangesBuildStepImplementation' => 'applications/changes/step/ChangesBuildStepImplementation.php',
    'ChangesConfigOptions' => 'applications/changes/config/ChangesConfigOptions.php',
    'ChangesNotifyCustomAction' => 'applications/changes/herald/ChangesNotifyCustomAction.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ChangesBuildStepImplementation' => 'HarbormasterBuildStepImplementation',
    'ChangesConfigOptions' => 'PhabricatorApplicationConfigOptions',
    'ChangesNotifyCustomAction' => 'HeraldCustomAction',
  ),
));
