<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ChangesBuildHelper' => 'applications/changes/helper/ChangesBuildHelper.php',
    'ChangesConfigOptions' => 'applications/changes/config/ChangesConfigOptions.php',
    'ChangesDiffRetryKeywordHandler' => 'applications/changes/keyword_handlers/ChangesDiffRetryKeywordHandler.php',
    'ChangesKeywordHandler' => 'applications/changes/keyword_handlers/ChangesKeywordHandler.php',
    'ChangesNotifyCustomAction' => 'applications/changes/herald/ChangesNotifyCustomAction.php',
    'DoorkeeperChangesFeedWorker' => 'applications/changes/doorkeeper/worker/DoorkeeperChangesFeedWorker.php',
    'DoorkeeperChangesFeedWorkerTestCase' => 'applications/changes/doorkeeper/worker/__tests__/DoorkeeperChangesFeedWorkerTestCase.php',
    'DoorkeeperChangesTestFeedWorker' => 'applications/changes/doorkeeper/worker/__tests__/DoorkeeperChangesTestFeedWorker.php',
    'TestKeywordHandler' => 'applications/changes/doorkeeper/worker/__tests__/DoorkeeperChangesFeedWorkerTestCase.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ChangesConfigOptions' => 'PhabricatorApplicationConfigOptions',
    'ChangesDiffRetryKeywordHandler' => 'ChangesKeywordHandler',
    'ChangesNotifyCustomAction' => 'HeraldAction',
    'DoorkeeperChangesFeedWorker' => 'DoorkeeperFeedWorker',
    'DoorkeeperChangesFeedWorkerTestCase' => 'PhabricatorTestCase',
    'DoorkeeperChangesTestFeedWorker' => 'DoorkeeperChangesFeedWorker',
    'TestKeywordHandler' => 'ChangesKeywordHandler',
  ),
));
